### ISSUE TITLE
Error: Undefined property: stdClass::$3.8.4

### ISSUE THREAD

**Issue by neradp** [KEINOS/Phar_Box3_installer#13]
I Cannot install box 3.8.4. Installer is giving this error.

Error: Undefined property: stdClass::$3.8.4

**Comment by KEINOS** [comment]
@neradp 

A happy new year and thank you for reporting!

I updated the manifest (checksum) files at a24788885d5d298ccf334713bb27c6130bf6c8e9. 

- Tested on: PHP 7.1.32 (Mac) and nightly build (Docker)

Will you check if it works for you?

If so, please close the issue. If not, please give us more of your env info. Such as PHP version and OS. Again, thanks for reporting!

**Comment by neradp** [comment]
It is now ok, thanks
